all:
  children:

    k8s_cluster:
      children:
        k8s_control_plane:
          hosts:
            cf-mes-cp-01:
              ansible_host: 10.8.101.11
            cf-mes-cp-02:
              ansible_host: 10.8.101.12
            cf-mes-cp-03:
              ansible_host: 10.8.101.13
        k8s_workers:
          hosts:
            cf-mes-wrk-01:
              ansible_host: 10.8.101.101    
            cf-mes-wrk-02:
              ansible_host: 10.8.101.102 
            cf-mes-wrk-03:
              ansible_host: 10.8.101.103 

    data_services:
      children:
        patroni:
          hosts:
            cf-mes-db-01:
              ansible_host: 10.8.103.11
            cf-mes-db-02:
              ansible_host: 10.8.103.12
            cf-mes-db-03:
              ansible_host: 10.8.103.13
        cache:
          hosts:
            cf-mes-cache-01:
              ansible_host: 10.8.102.11
            cf-mes-cache-02:
              ansible_host: 10.8.102.12
            cf-mes-cache-03:
              ansible_host: 10.8.102.13

    equipment:
      hosts:
        cf-eap-01:
          ansible_host: 10.8.150.11
          fab: 1
        cf-eap-02:
          ansible_host: 10.8.150.12
          fab: 2
        cf-eap-03:
          ansible_host: 10.8.150.13
          fab: 3

    # OS groups: Hosts appear in both a role group and an OS group
    rhel:
      hosts:
        cf-mes-cp-01:
        cf-mes-cp-02:
        cf-mes-cp-03:
        cf-mes-wrk-01:
        cf-mes-wrk-02:
        cf-mes-wrk-03:
        cf-mes-db-01:
        cf-mes-db-02:
        cf-mes-db-03:

    ubuntu:
      hosts:
        cf-mes-cache-01:
        cf-mes-cache-02:
        cf-mes-cache-03:
        cf-eap-01:
        cf-eap-02:
        cf-eap-03:

    template_source:
      hosts:
        {}
    