all:
  children:

    k8s_cluster:
      children:
        k8s_control_plane:
          hosts:
            cf-mes-cp-01:
              ansible_host: 10.8.101.11
        k8s_workers:
          hosts:
            cf-mes-wrk-01:
              ansible_host: 10.8.101.101

    data_services:
      hosts:
        cf-mes-cache-01:
          ansible_host: 10.8.102.11
          services: [redis, kafka]
        cf-mes-db-01:
          ansible_host: 10.8.103.11
          services: [patroni, postgresql]

    equipment:
      hosts:
        cf-lcs-01:
          ansible_host: 10.8.150.11
          fab: 1

    # OS groups — hosts appear in both a role group and an OS group
    rhel:
      hosts:
        cf-mes-cp-01:
        cf-mes-wrk-01:
        cf-mes-db-01:

    ubuntu:
      hosts:
        cf-mes-cache-01:
        cf-lcs-01:
